### ISSUE TITLE
Cannot run demos

### ISSUE THREAD

**Issue by mrpmorris** [SteveSandersonMS/WebWindow#111]
I downloaded the project, opened the WebWindow.Samples solution, and then tried to run a project.

All three crash on start up with the following error:

```
---------------------------
Error instantiating webview
---------------------------
The system cannot find the file specified.
---------------------------
OK   
---------------------------
```

**Comment by Donaut** [comment]
If you using windows you need to install the Microsoft Edge first. And i suggest you to read previous issues as well to know what typical errors the project has.

**Comment by mrpmorris** [comment]
Bah. I must have left "is:open" in the search criteria.

Seems having Edge installed isn't enough, I needed the newest beta.

Thanks
