### ISSUE TITLE
Write some contributing guidelines

### ISSUE THREAD

**Issue by festim-deari** [SteveSandersonMS/WebWindow#12]
Hi @SteveSandersonMS,

I would love to contribute on this project. Could you please write some contributing guidelines, and some issues to help you with?

**Comment by SteveSandersonMS** [comment]
Thanks for offering, @festim-deari!

What kinds of features would you most want to add? If you know C++ then the most urgent thing I think is to clean up the implementation of the native parts, as it’s very messy currently. I expect it doesn’t always free the allocated memory correctly. The second most valuable thing would be to add some tests that cover end-to-end usage (ie they actually open windows and check that the .NET code can interact with them properly). 

As for contributing guidelines, I just ask that if you’re adding any features you support all three platforms. 

Thanks!
