### ISSUE TITLE
Dark Theme and TitleBar Customization

### ISSUE THREAD

**Issue by Mercurial** [SteveSandersonMS/WebWindow#21]
Hey, first of all awesome work you have here! I have been following you since when Blazor was still pretty experimental! I have no doubt this will be a major success as-well as Blazor!

Anyway my question is, how easy would it be to adapt or force a current theme in a specific OS? Lets say Windows Dark Theme, so for example I would have dark theme title bar or just customize it in general!

I know its pretty early but I'm just wondering if this was something trivial or I might need to go into C++ / Objective C world or wait for the project to mature?

Thanks!
You are really changing the world Steve, keep it up!

**Comment by SteveSandersonMS** [comment]
I expect this isn't trivial, but I'm sure it could be achieved by adding implementation in the native code for each platform. If this is something you're interested in contributing, please consider submitting a PR. Thanks!
