### ISSUE TITLE
Running error on windows

### ISSUE THREAD

**Issue by quan0zhou** [SteveSandersonMS/WebWindow#23]
Console program running error
`  static void Main(string[] args)
        {
            var window = new WebWindow("My first WebWindow app");
            window.NavigateToString("test");
            window.WaitForExit();
        }`
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>

**Comment by tbonham** [comment]
I'm also receiving the same error and I haven't figured out who to fix it.

**Comment by SteveSandersonMS** [comment]
Do you have Edge Beta installed?

**Comment by quan0zhou** [comment]
After Edge Beta installation, the problem is solved, thank you

**Comment by thomaslevesque** [comment]
Even though the fix is simple, I think this issue should be addressed. A specific exception should be thrown instead of `AccessViolationException`, e.g. `InvalidOperationException` with message "Could not find a supported browser on this system".

**Comment by SteveSandersonMS** [comment]
@thomaslevesque I agree. If you’re able to submit a PR for this I’d be happy to merge it.

**Comment by thomaslevesque** [comment]
@SteveSandersonMS I'd love to, but after looking into it, I'm afraid the problem is in the native C++ code, and my C++ skills are limited...

**Comment by kartik786-git** [comment]
After Edge Beta installation this issue not fixed. Please help me

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
