### ISSUE TITLE
Error instancing webwiew

### ISSUE THREAD

**Issue by patricka2** [SteveSandersonMS/WebWindow#25]
Hi i run HelloWorldApp	sample and confront with this error

![Untitled](https://user-images.githubusercontent.com/46094177/69866306-f9a76100-12b8-11ea-92b6-ec783d8cdf70.png)

![Untitle4](https://user-images.githubusercontent.com/46094177/69866858-7f77dc00-12ba-11ea-98d3-dfc72bfa64b4.png)

**Comment by tbonham** [comment]
How did you fix this error. I receive the samething when I tried to run it.

**Comment by patricka2** [comment]
I just install edge chromium and it works. @tbonham
