### ISSUE TITLE
Remove preview?

### ISSUE THREAD

**Issue by timheuer** [SteveSandersonMS/WebWindow#29]
https://github.com/SteveSandersonMS/WebWindow/blob/790952d9231ab970969ebc2d1cc449f705210c07/Directory.Build.props#L5

**Comment by SteveSandersonMS** [comment]
The `Microsoft.AspNetCore.Blazor` package is still in preview, so this needs to stay for now.

I'm sure it would be possible to replace this with `Microsoft.AspNetCore.Components` (which is RTM already) though whatever extra bits from `.Blazor` are being depended on here would need to be duplicated. For now I think this isn't an urgent need so I'm tending to leave this dependency as-is.
