### ISSUE TITLE
Suggestion: Window resize event on monitor change

### ISSUE THREAD

**Issue by sondreb** [SteveSandersonMS/WebWindow#37]
Moving the window from one screen to another with a different DPI, won't resize the app. A quick resize of the window and the app resizes (font-size, etc.).

Perhaps the WebWindow should auto-trigger a single resize event (or similar to cause re-render) when it notices a movement from one screen to another?

**Comment by SteveSandersonMS** [comment]
I'd be happy to consider a PR for this. Please feel free to submit one if this is an important scenario in your case.

TBH I'm surprised this isn't handled by the native web view control, so if you're reporting this regarding Windows, maybe it would be better reported as an issue to the WebView2 maintainers.
