### ISSUE TITLE
Blazor not working on Windows Edge Version 80.0.355.1 

### ISSUE THREAD

**Issue by tomlm** [SteveSandersonMS/WebWindow#39]
My OS was upgraded this morning and now BlazorDesktopApp sample is not working.  

I have several other Blazor based samples I was working with and they all stopped working at the same time:
![image](https://user-images.githubusercontent.com/17789481/70660421-feeca000-1c16-11ea-88a8-1589afa05c04.png)

New version of Edge chromium?

**Comment by tomlm** [comment]
FYI: My build was the Edge Dev Channel.
I downgraded to the Edge Beta Channel and everything started working again.
![image](https://user-images.githubusercontent.com/17789481/70662840-e6cb4f80-1c1b-11ea-9d28-8a3e9f7b6c4c.png)

**Comment by Berrysoft** [comment]
Pull Request here: #31 
It is because that Edge Dev deprecates an API.

**Comment by Berrysoft** [comment]
We decided at last to follow Edge Beta. To get the version compatible with Edge Dev, checkout [edgedev](https://github.com/Berrysoft/WebWindow/tree/edgedev) branch.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @Berrysoft!
