### ISSUE TITLE
Suggestion: OnExit Event

### ISSUE THREAD

**Issue by alexhorner** [SteveSandersonMS/WebWindow#40]
This would be another event which would fire upon window exit and would be useful to handle events for the closing of a window rather than having to depend upon WaitForExit()

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion! If more people request this I'll consider it, though for now just adding code after `WaitForExit` seems sufficient to me.

**Comment by eivarin** [comment]
I need this
