### ISSUE TITLE
what about the support plan for WPF based desktop application that target .net core ? 

### ISSUE THREAD

**Issue by DavidSilwal** [SteveSandersonMS/WebWindow#48]

**Comment by MaverickMartyn** [comment]
What do you mean?
That project has a completely different scope than this one.
This project aims to be a cross-platform UI solution, whereas WPF for .NET Core will be Windows only.
WPF is not, and likely never will be, cross-platform.

**Comment by 199621616** [comment]
跨平台还有很长的路要走。但是支持WPF与WinForm，则可立即见效。让用户先把能做的事做起来。跨平台，再逐步扩展啊。
