### ISSUE TITLE
Getting Error instanciating webview when I try to run the helloworld sample

### ISSUE THREAD

**Issue by anaselhajjaji** [SteveSandersonMS/WebWindow#59]
![image](https://user-images.githubusercontent.com/3309485/73568058-a1661a00-4435-11ea-8461-51967e846d1f.png)

![image](https://user-images.githubusercontent.com/3309485/73568101-bc388e80-4435-11ea-84ca-92623ebedd36.png)

**Comment by vavadevds** [comment]
Hi, @anaselhajjaji I think just you need to install the new Microsoft Edge
https://www.microsoft.com/en-us/edge?form=MY01BQ&OCID=MY01BKQ

**Comment by vladimir-novoseltsev** [comment]
I get the same error even with new Edge installed. WebWindow/0.1.0-20191120.6

**Comment by anaselhajjaji** [comment]
It was solved for me when I installed Microsoft Edge Beta.

**Comment by benwurth** [comment]
Still did not work for me even when I downloaded the new Microsoft Edge Beta.

**Comment by SteveSandersonMS** [comment]
Sorry for the inconvenience. This problem will go away once the library is updated to work with the latest Edge on Windows.
