### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by NicolasDorier** [SteveSandersonMS/WebWindow#6]
Trying to run sample

![image](https://user-images.githubusercontent.com/3020646/69117988-14b5ec00-0ad5-11ea-8c60-d976ec34cd2b.png)

**Comment by AntonScharnick** [comment]
You need to install the new Chromium based Edge if you're on Windows: https://www.microsoftedgeinsider.com/en-us/.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @AntonScharnick!

Yes, the library could detect this and fall back on older Edge, but I haven't implemented that. If someone's interested in doing so, please consider sending a PR!

**Comment by NicolasDorier** [comment]
Thanks, a better error message would go a long way.

**Comment by SteveSandersonMS** [comment]
Great suggestion. If you’re able to submit a PR for this, that would be perfect.

**Comment by Bartmax** [comment]
I'm having this error even I have chromium edge installed. @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
You need Edge from its Canary/Beta channels, *not* just the stable channel. You can have more than one channel installed at the same time.
