### ISSUE TITLE
Cycle Detected with dotnet add

### ISSUE THREAD

**Issue by isaacrlevin** [SteveSandersonMS/WebWindow#60]
I am trying to use the pre-built nuget package, and when I add it via the CLI, I get

> Error	NU1108	Cycle detected. 
  WebWindow -> WebWindow (>= 0.1.0-20191120.6).	WebWindow	C:\dev\WebWindow\WebWindow\WebWindow.csproj	1	

Not sure what could be  the cause of this. I have node and C++ installed

**Comment by zeroskyx** [comment]
I believe the problem is that your project's name is WebWindow and thus the reference in the .csproj file is not interpreted as a NuGet package but as a reference to itself.

Try changing your project name to something else like **WebWindowTest**

Enjoy!
