### ISSUE TITLE
Support for ARM/ ARM64

### ISSUE THREAD

**Issue by zeroskyx** [SteveSandersonMS/WebWindow#61]
Greetings,

and thank you for this amazing project.

Would it be possible for you to add support for ARM/ ARM64? Currently only native artifacts for linux-x64, osx-x64 and win-x64 are generated, making it impossible for usage on devices such as a Raspberry Pi.

Thanks in advance and best regards
-Simon

**Comment by SteveSandersonMS** [comment]
Great idea! I'd be happy to consider accepting a PR that adds this functionality if you want to submit one.
