### ISSUE TITLE
Enable the GitHub dependant page/button

### ISSUE THREAD

**Issue by paolofulgoni** [SteveSandersonMS/WebWindow#62]
GitHub has this nice feature that shows [dependant projects](https://help.github.com/en/github/visualizing-repository-data-with-graphs/listing-the-projects-that-depend-on-a-repository), both via the [dependants page](https://github.com/SteveSandersonMS/WebWindow/network/dependents) and a nice "Used by" button.

I think that this feature would be useful to understand how widely is this project used, at least in the open-source world.

I don't know how to to this, maybe a `.nuspec` file is enough.

**Comment by SteveSandersonMS** [comment]
Interesting idea. If you figure out how to do this then please let us know. Thanks!

**Comment by Code-DJ** [comment]
@SteveSandersonMS per this https://github.com/dipy/dipy/issues/1856 looks like an email needs to be sent to github support to make it happen. I assume the email has to be sent by repo owner.

**Comment by IvanJosipovic** [comment]
I believe that this feature requires a few entries in the .csproj for it work correctly.

I reviewed a couple .Net projects that have this feature working:
 - https://github.com/chanan/BlazorTypography/blob/master/src/BlazorTypography/BlazorTypography.csproj
 - https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/GoogleMapsComponents.csproj
 - https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/Blazorise.csproj
 - https://github.com/egil/razor-components-testing-library/blob/master/src/Egil.RazorComponents.Testing.Library.csproj
 - https://github.com/nheath99/NodaTimePicker/blob/master/src/NodaTimePicker/NodaTimePicker.csproj

All the working projects seem to have the following entries in the csproj:
- PackageId
- PackageProjectUrl
- RepositoryUrl
