### ISSUE TITLE
Unable to load DLL 'WebWindow.Native'

### ISSUE THREAD

**Issue by parabeyond008** [SteveSandersonMS/WebWindow#66]
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'WebWindows.WebWindow' threw an exception.
  Source=WebWindow
  StackTrace:
   at WebWindows.WebWindow..ctor(String title)
   at HelloWorldApp.Program.Main(String[] args) in D:\WebWindow-master\samples\HelloWorldApp\Program.cs:line 10

内部异常 1:
DllNotFoundException: Unable to load DLL 'WebWindow.Native' or one of its dependencies: 找不到指定的程序。 (0x8007007F)

**Comment by SteveSandersonMS** [comment]
It works OK when I follow the [build instructions](https://github.com/SteveSandersonMS/WebWindow#how-to-build-this-repo). Please check you followed the instructions fully, including setting the build config to x64.
