### ISSUE TITLE
Does WebWindow support Linux 32bit arch?

### ISSUE THREAD

**Issue by anaselhajjaji** [SteveSandersonMS/WebWindow#68]
I have an error like: DllNotFoundException: Unable to load DLL 'WebWindow.Native' or one of its dependencies: The specified module could not be found.

I think that because WebWindow does not support 32bit yet? is this correct? If yes, any plan to support it?

**Comment by SteveSandersonMS** [comment]
It's only built in 64 bit currently. If you're interested in submitting a PR to add 32-bit support, I'd be happy to consider merging it. Thanks!
