### ISSUE TITLE
Is there anyway to force a window to quit without closing it manually

### ISSUE THREAD

**Issue by ajmcateer** [SteveSandersonMS/WebWindow#7]
I was playing around with this library and I am launching multiple windows in their own thread and tracking them in a dictionary. I just found out .net core removed thread.abort();

I am trying to find a way to force the window to close by the main program but at the moment there doesn't seem to be one. Would you be able to suggest any method?

I would also appreciate it if you could suggest any reading or some way to get me up to speed with what you are doing I would like to start contributing I have several ideas, but I am not very familiar with C++ interop.

**Comment by SteveSandersonMS** [comment]
I haven't implemented this, but it would be nice if `WebWindow` implemented `IDisposable`, and calling dispose made it close the window. If you're interested, please consider sending a PR!

> I would also appreciate it if you could suggest any reading or some way to get me up to speed with what you are doing I would like to start contributing I have several ideas, but I am not very familiar with C++ interop.

The overall approach used for C++ interop here is this: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke
