### ISSUE TITLE
Any idea how to use it for ARM 64?

### ISSUE THREAD

**Issue by anaselhajjaji** [SteveSandersonMS/WebWindow#70]
I'm trying to use it in Raspberry Pie 3 ou 4 (both on ARM 64).
I'm getting the initialization issue of teh webview : Unable to load shared library 'WebWindow.Native' or one of its dependencies.
Do you have any ideas about that?

**Comment by JinShil** [comment]
Hi @anaselhajjaji   
I'm not the author of this repository, so I don't want to speak for him, but I don't think this repository is being maintained anymore.  I also needed Blazor Hybrid on the Raspberry Pi 3 and 4 and could never get this or Photino to work properly.  So I crated the following as alternatives:
https://github.com/JinShil/BlazorWebView
https://github.com/JinShil/WebWindow
I hope they will help you.
