### ISSUE TITLE
Edge stable or Edge beta?

### ISSUE THREAD

**Issue by eivarin** [SteveSandersonMS/WebWindow#72]
So, I'm setting up another pc for programming and when I went to download edge I realized that microsoft has already realized the first stable version of the new edge. The thing is every issue related to setting up the stuff needed to use WebWindow says that we need to install edge beta.

Can we use the stable version for testing? as it would be what clients/users of our programs, which use WebWindow, would use.

**Comment by frankhale** [comment]
I say try it out and see if it works then come back and report here so others will know =)

**Comment by SandroRiz** [comment]
With Edge stable the samples works fine

**Comment by eivarin** [comment]
It Works with the stable for now so i'm closing this issue
