### ISSUE TITLE
Naming and Window.external deprecated?

### ISSUE THREAD

**Issue by iqmeta** [SteveSandersonMS/WebWindow#8]
Hi,
saw on cpp code the overwrite, but does it might make sense 
or is it possible to name it something onw?

https://developer.mozilla.org/en-US/docs/Web/API/Window/external

Cheers. Great Project!

**Comment by SteveSandersonMS** [comment]
With this library `window.external` has a completely different meaning to the old API you're linking to. It's unrelated :)
