### ISSUE TITLE
How to disable right click???

### ISSUE THREAD

**Issue by eivarin** [SteveSandersonMS/WebWindow#80]
So, I know webwindow runs on the webview2 API that comes with the new Edge Chromium.

Would there be a way to completely disable the browser right click that opens the browser options?
It isn't really convenient for someone who is trying to make browser design look native

**Comment by eivarin** [comment]
So I found out that to do this u need to update the WebView2 to the new version (0.9.430) and update the methods name in c++ .
Working on it at the moment.

**Comment by jinqi166** [comment]
You need this code on js side
`window.οncοntextmenu=function(){return false;}  `

**Comment by eivarin** [comment]
thanks, it worked for me although i did it in a different way
`<body oncontextmenu="return false;">`
anyway thanks @jinqi166
